### ISSUE TITLE
Error in Schmitt method for Kp calculation of multi-charged compounds

### ISSUE THREAD

**Issue by Vincent-AC** [metrumresearchgroup/PBPK_PC#2]
Hello,

I know the paper is already published (and what a nice paper it is!) so my comment might have little impact but still, since I use your codes I will inform you of what I might have found.

I think that i found an error in the CalcKp_Schmitt.R file.

The formula for K_neutral_lipids is the following: 
`K_n_l <- K_n_pl*(F1*F2 + alpha*((1-F1)*F2 + F1*(1-F2)) + (1-F1)*(1-F2))`

However in the Schmitt paper it is told that K_n_l = K_n_pl * (F_neutral * alpha * Fcharged)
So assuming that the number of charges does not influence the distribution coefficient (hence alpha is valid for mono- and bi-charged forms.) the K_n_pl equation should be the following: 

`K_n_l <- K_n_pl*(F1*F2 + alpha*( (1-F1)*F2 + F1*(1-F2) + (1-F1)*(1-F2) ) )`

I moved the closing parenthesis to include (1-F1)*(1-F2) in it since it calculates the fraction that has two charges. The initial formula might have been copy-pasted from zwitterions ?

Best regards,
Vincent

**Comment by aelmokadem** [comment]
Hi Vincent,

Thank you for your comment and your interest in our work. We will take a closer look at this and make the necessary adjustment if need be.

Best,
Ahmed.

**Comment by kmutsey** [comment]
Hi Vincent,

Thank you for bringing this error to our attention. We have made the correction in the CalcKp_Schmitt.R script and have added a note to the README file.

Kind regards,
Kiersten

**Comment by Vincent-AC** [comment]
Thanks !
