### ISSUE TITLE
Negative Partition Coefficients

### ISSUE THREAD

**Issue by Parsshava** [metrumresearchgroup/PBPK_PC#3]
Hi,

I was trying to calculate the Kps using R&R:

#Sertraline, #Monoprotic Base
`calcKp_RR(5.06, pKa=9.56, 0.018, BP=1, type=3, dat)`

These are the set of outputs I get. I am trying to understand why I would get negative Kps for heart and liver, please can you explain.
```
$Kpad
[1] 1.863933

$Kpbo
[1] 0.9800989

$Kpbr
[1] NA

$Kpgu
[1] 0.3940665

$Kphe
[1] -0.1640726

$Kpki
[1] 0.04823522

$Kpli
[1] -0.07172251

$Kplu
[1] 0.03903482

$Kpmu
[1] 0.0565975

$Kppa
[1] 0.4233503

$Kpsk
[1] 0.2838334

$Kpsp
[1] 0.01170823
```

Thanks

**Comment by kierstenu** [comment]
Hi Parsshava,

The problem of negative Kps for some monoprotic bases using the R&R method has been identified previously (see this discussion: https://github.com/metrumresearchgroup/mrgsolve/discussions/795).
Based on the inputs you provided, the value of Ka_AP is negative, which is causing some of the Kps to be negative. I don't have any other insights, so it may be worth communicating with the method authors to get their thoughts.

**Comment by Parsshava** [comment]
Thanks @kierstenu. Will reach out to the Authors.

**Comment by Parsshava** [comment]
Hi @kierstenu 

I tried to find a fix for the negative Ka_AP, it is because of `Kpu_bc <- (HCT - 1 + BP)/(HCT*fup)`. The fup at the end was missing and causing it to run into negative values. Can you check from your end.

Attaching a link to a journal:
10.1124/dmd.119.087973

**Comment by kierstenu** [comment]
Hi Parsshava,

Thank you for bringing this error to our attention. We have made the correction in the CalcKp_R&R.R script and have added a note to the README file.

Best,
Kiersten
